
### GET ME
GET http://localhost:3000/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY0NTkyODY4OCwiZXhwIjoxNjQ1OTMyMjg4fQ.xA-Yy4gswBl6Z2kM2BjQgvqCQAx6E_hrbXO9Da3sV0w

### Get User by Username
GET http://localhost:3000/users/test1
