### REGISTER USER
POST http://localhost:3000/auth/register
Content-Type: application/json

{
	"email": "test@test.test",
	"username": "test",
	"password": "Test1234$"
}

### Login USER
POST http://localhost:3000/auth/login
Content-Type: application/json

{
	"email": "test@test.test",
	"password": "Test1234$"
}
